# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_regional", "0002_reset_pk_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("retention_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads_default_channels",
                        to="django_regional.language",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(blank=True, related_name="leads_channels", to="django_regional.language"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=253)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("MANUFACTURER", "Manufacturer"),
                            ("WHOLESALE", "Wholesale"),
                            ("RETAILER", "Retailer"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("industry", models.CharField(blank=True, default="", max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("platform", models.CharField(blank=True, default="", max_length=64)),
                ("hooks", models.JSONField(blank=True, default=list)),
                ("stage_entered_at", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv", "CSV import"),
                            ("form", "Contact form"),
                            ("manual", "Manual"),
                            ("connector", "Connector"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_ref", models.CharField(blank=True, default="", max_length=128)),
                ("do_not_contact", models.BooleanField(default=False)),
                ("customer_uid", models.UUIDField(blank=True, null=True)),
                ("rotation_count", models.PositiveSmallIntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="companies", to="django_leads.channel"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("first_name", models.CharField(blank=True, default="", max_length=128)),
                ("last_name", models.CharField(blank=True, default="", max_length=128)),
                ("job_title", models.CharField(blank=True, default="", max_length=128)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv", "CSV import"),
                            ("form", "Contact form"),
                            ("manual", "Manual"),
                            ("connector", "Connector"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("consent", "Consent (art. 6(1)(a))"),
                            ("legitimate_interest", "Legitimate interest (art. 6(1)(f))"),
                            ("contract", "Contract (art. 6(1)(b))"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("consent_ref", models.IntegerField(blank=True, null=True)),
                ("opt_out_at", models.DateTimeField(blank=True, null=True)),
                ("anonymised_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="django_leads.company"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("form", "Form"),
                            ("stage", "Stage"),
                            ("rule", "Rule"),
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("reply", "Reply"),
                            ("bounce", "Bounce"),
                            ("optout", "Opt-out"),
                            ("note", "Note"),
                            ("anonymised", "Anonymised"),
                            ("blocked", "Blocked"),
                            ("skipped", "Skipped"),
                            ("rotation", "Rotation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("actor", models.CharField(default="system", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="django_leads.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="django_leads.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv", "CSV import"),
                            ("form", "Contact form"),
                            ("manual", "Manual"),
                            ("connector", "Connector"),
                        ],
                        default="csv",
                        max_length=16,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("report", models.JSONField(blank=True, default=list)),
                ("created_by", models.CharField(blank=True, default="", max_length=150)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="django_leads.channel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "import batches",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=128)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[("open", "Open"), ("won", "Won"), ("lost", "Lost"), ("unresponsive", "Unresponsive")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("is_terminal", models.BooleanField(default=False)),
                ("on_reply", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stages", to="django_leads.channel"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="companies", to="django_leads.stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("company", "email"),
                name="leads_contact_company_email_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(fields=("channel", "key"), name="leads_stage_channel_key_uniq"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["channel", "stage"], name="leads_company_channel_stage"),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(fields=("channel", "domain"), name="leads_company_channel_domain_uniq"),
        ),
    ]
