# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_leads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importbatch",
            name="content",
        ),
        migrations.AddField(
            model_name="importbatch",
            name="last_row_done",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="row_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("form", "Form"),
                    ("stage", "Stage"),
                    ("rule", "Rule"),
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("reply", "Reply"),
                    ("bounce", "Bounce"),
                    ("optout", "Opt-out"),
                    ("note", "Note"),
                    ("anonymised", "Anonymised"),
                    ("blocked", "Blocked"),
                    ("skipped", "Skipped"),
                    ("rotation", "Rotation"),
                    ("legal_basis", "Legal basis"),
                    ("legal_basis_conflict", "Legal basis conflict"),
                ],
                max_length=32,
            ),
        ),
    ]
