# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_leads", "0002_import_batch_no_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("form", "Form"),
                    ("stage", "Stage"),
                    ("rule", "Rule"),
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("reply", "Reply"),
                    ("bounce", "Bounce"),
                    ("optout", "Opt-out"),
                    ("note", "Note"),
                    ("anonymised", "Anonymised"),
                    ("blocked", "Blocked"),
                    ("skipped", "Skipped"),
                    ("rotation", "Rotation"),
                    ("legal_basis", "Legal basis"),
                    ("legal_basis_conflict", "Legal basis conflict"),
                    ("intel", "Intel"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="StageRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("stage_entered", "Stage entered"), ("intel_ready", "Intel ready")], max_length=16
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("request_audit", "Request audit"), ("communicate", "Communicate")],
                        default="communicate",
                        max_length=16,
                    ),
                ),
                ("template_key", models.CharField(blank=True, default="", max_length=128)),
                (
                    "contact_strategy",
                    models.CharField(
                        choices=[("primary", "Primary contact"), ("ai_pick", "AI pick")],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("require_hooks", models.BooleanField(default=True)),
                ("require_email", models.BooleanField(default=True)),
                ("require_legal_basis", models.BooleanField(default=True)),
                ("cooldown_hours", models.PositiveIntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="django_leads.channel"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="django_leads.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(default="leads.analysis", max_length=64)),
                ("prompt_text", models.TextField()),
                ("json_schema", models.JSONField(default=dict)),
                ("model", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_profiles",
                        to="django_leads.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(fields=("channel", "key"), name="leads_analysisprofile_channel_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="RecipientPickProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(default="leads.pick_recipient", max_length=64)),
                ("prompt_text", models.TextField()),
                ("json_schema", models.JSONField(default=dict)),
                ("model", models.CharField(max_length=128)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_profiles",
                        to="django_leads.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(fields=("channel", "key"), name="leads_recipientprofile_channel_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="RuleRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fired_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("fired", "Fired"),
                            ("skipped", "Skipped"),
                            ("blocked", "Blocked"),
                            ("cooldown", "Cooldown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rule_runs", to="django_leads.company"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="django_leads.stagerule"
                    ),
                ),
            ],
            options={
                "ordering": ["-fired_at", "-id"],
                "indexes": [models.Index(fields=["rule", "company", "-fired_at"], name="leads_rulerun_rule_company")],
            },
        ),
    ]
