# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-14 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_leads", "0004_activity_form_import_failed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=128, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("claimed", "Claimed"), ("done", "Done"), ("retry", "Retry"), ("failed", "Failed")],
                        default="claimed",
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=64)),
                ("failures", models.PositiveSmallIntegerField(default=0)),
                ("attempted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="rulerun",
            name="event_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="rulerun",
            name="state",
            field=models.CharField(
                choices=[("claimed", "Claimed"), ("done", "Done"), ("retry", "Retry"), ("failed", "Failed")],
                default="done",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("form", "Form"),
                    ("form_import_failed", "Form import failed"),
                    ("stage", "Stage"),
                    ("rule", "Rule"),
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("reply", "Reply"),
                    ("bounce", "Bounce"),
                    ("optout", "Opt-out"),
                    ("note", "Note"),
                    ("anonymised", "Anonymised"),
                    ("blocked", "Blocked"),
                    ("skipped", "Skipped"),
                    ("rotation", "Rotation"),
                    ("rotation_failed", "Rotation failed"),
                    ("rotation_gave_up", "Rotation gave up"),
                    ("legal_basis", "Legal basis"),
                    ("legal_basis_conflict", "Legal basis conflict"),
                    ("intel", "Intel"),
                    ("intel_empty", "Intel empty"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rulerun",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[("fired", "Fired"), ("skipped", "Skipped"), ("blocked", "Blocked"), ("cooldown", "Cooldown")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="rulerun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_key", ""), _negated=True),
                fields=("rule", "company", "event_key"),
                name="leads_rulerun_event_uniq",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="claims", to="django_leads.company"
            ),
        ),
    ]
