# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Generated by Django 6.1.1 on 2026-09-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_leads", "0005_claims_rotation_retry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErasedAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=254, unique=True)),
            ],
            options={
                "verbose_name_plural": "erased addresses",
            },
        ),
    ]
